baseurl = "http://mapamundi.me/"
languageCode = "en-us"
title = "Mapa Mundi"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Mapamundi"
	description = "Mapamundi"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar2_lzn.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "'Por un mundo donde seamos socialmente iguales, humanamente diferentes y totalmente libres'.  ([Rosa Luxemburg] (https://es.wikipedia.org/wiki/Rosa_Luxemburgo))"
		# The icons will be shown if you enter your username
		twitter = "calcita3"
		github = "calcita"
		gitlab = ""
		dribbble = ""
		vimeo = "mapamundi"
		flickr = "mapa_mundi"
		linkedin = ""

		copyright = [
			 "El sitio está construido utilizando el software libre [R] (https://www.r-project.org/) y su contenido está realizado por Gabriela Mathieu y publicado bajo la licencia libre (CC BY-SA 4.0) [Creative Commons - Atribución - Compartir Igual 4.0 Internacional](//https://creativecommons.org/licenses/by-sa/4.0/deed.es). ![CC](/images/cc-by-sa.png)"
			 ]

	[params.about]
		hide  = false
		title = "Mapamundi"
		content = "**dober dan** - hvala - **faleminderit** - blagodarya - **efcharistó** - gràcies -**merci**- thank you - **grazie** - obrigado - **danke** . Mi lista de cómo decir gracias en el idioma de los países que he visitado. Intento de aprenderla antes de llegar pero a veces me voy sin saber decir 'gracias'."


	[params.portfolio]
		hide  = false
		title = "Fotos recientes"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0005.jpg" 
			thumb = "thumbs/201709_Berlin_0005.jpg"
			title = "Rosa Luxemburg, estación de metro"
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0012.jpg"
			thumb = "thumbs/201709_Berlin_0012.jpg"
			title = "Transporte"
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0048.jpg"
			thumb = "thumbs/05.jpg"
			title = "Stop wars"
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0186.jpg"
			thumb = "thumbs/201709_Berlin_0186.jpg"
			title = "Mi vida"
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0050.jpg"
			thumb = "thumbs/201709_Berlin_0050.jpg"
			title = "The future is female"
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

		[[params.portfolio.gallery]]
			image = "fulls/201709_Berlin_0716.jpg"
			thumb = "thumbs/201709_Berlin_0716.jpg"
			title = ""
			description = "[Álbum de fotos](https://www.flickr.com/people/mapa_mundi/)"

	[params.recentposts]
		hide  = false
		title = "Artículos recientes"

	[params.contact]
		hide  = false
		title = "Contactame"
		content = "Si quieres saber más sobre mi viaje puedes enviarme un mensaje, tan pronto como pueda te responderé."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "-56,-33"
		address = [

		
		]

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "mapamundi@gmx.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nombre / Name"
			email = "Email"
			message = "Mensaje /Message"
			submit = "Enviar /Send"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
	
[[menu.main]]
	name = "Tags"
	url  = "tags/"
	weight = 0
	
[[menu.main]]
	name = "About"
	url  = "about/"
	weight = 0
