baseURL = "http://mapamundi.me/"
languageCode = "es-ES"
title = "Mapa Mundi"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3


[params]
logo = "images/logo.png"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "'Por un mundo donde seamos socialmente iguales, humanamente diferentes y totalmente libres'. (Rosa Luxemburg)"
# about author
author = "Gabriela Mathieu"
authorImage = "images/header-bg.jpg"
shortDescription = "El contenido de este blog, las fotos, videos, mapas, gráficos y textos están elaborados por [mi](//linkedin.com/in/mathieugabriela) -salvo que mencione lo contrario- y publicado bajo una licencia [*Creative Commons - Atribución - Compartir Igual 4.0 Internacional* (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/). El sitio lo elaboré utilizando el software libre  [*R*](//r-project.org/) y el tema de [Hugo](//gohugo.io/) ['Parsa']([themefisher.com](themefisher.com). Las fotos las alojé en [Flickr](//flickr.com/photos/mapa_mundi/) y los videos en [Vimeo](//vimeo.com/user71114775/). Utilizo un lenguaje no sexista porque lo que no se nombra no existe -incluyo una 'x' siempre que sea necesario-. ![](img/cc-by-sa.png)"
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "[CC-SA-BY 4.0 Internacional](//creativecommons.org/publicdomain/zero/1.0/)"

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = ""
  accessToken = ""

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "Montevideo"
    
    [[params.footer.addresses]]
    address = "Uruguay"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = ""
    
    [[params.footer.contacts]]
    contactInfo = "Mail: calcita@gmx.li"


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "//twitter.com/calcita3"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "//lindekin.com/mathieugabriela"
  
  [[params.social]]
  icon = "ti-github"
  URL = "//github.com/calcita"
