---
title: Recorrido
author: ''
date: '2017-10-11'
slug: recorrido
categories:
  - mapa
tags: []
---

Probando
```{r, echo=FALSE}
#library(leaflet)
#city=read.csv("/home/calcita/myblog/Insumos_blog/city_latlon.csv")  
# m <- leaflet() %>%
#     addTiles() %>%  # Add default OpenStreetMap map tiles
# addMarkers(lng=13.3886, lat=52.5172,
#    popup="Ich bin hier")
# m  # Print the map
  
#### hacer un gif
#probar esto  
#m<-leaflet() %>% 
#  addTiles()%>% 
#  addMarkers(lng=city$Longitude,lat=city$Latitude, data=city,popup=~City) %>% 
#    setView(m,lng=city$Longitude[5],lat=city$Latitude[5],zoom=4.5)%>% 
#      addPolylines(lng = city$Longitude, lat =city$Latitude, layerId = NULL, group = NULL,
#      stroke = TRUE, color = "#03F", weight = 2.5, opacity = 0.5,
#      fill = FALSE, fillColor = "blue", fillOpacity = 0.2, dashArray = NULL,
#      smoothFactor = 1, noClip = FALSE, popup = NULL, popupOptions = NULL,
#      label = NULL, labelOptions = NULL, options = pathOptions(),
#      highlightOptions = NULL, data = getMapData(m))
#m
```

```{r, echo=FALSE}
library(leaflet)
city=read.csv("/home/calcita/myblog/Insumos_blog/city_latlon.csv")  
m<-leaflet() %>%
   addTiles()%>% 
   setView(m,lng=9.168,lat=48.803,zoom=4)%>% 
   #setMaxBounds(m,lng1=-12.041,lng2=46.770,lat1=60.436,lat2=35.317)%>%
    addMarkers(lng=city$Longitude,lat=city$Latitude, data=city,popup=~Label) %>% 
   addPolylines(lng = city$Longitude, lat =city$Latitude, layerId = NULL, group = NULL,
                stroke = TRUE, color = c("blue","red"), weight = 2.5, opacity = 0.5,
                fill = FALSE, fillColor = c("blue"), fillOpacity = 0.2, dashArray = NULL,
                smoothFactor = 1, noClip = FALSE, popup = NULL, popupOptions = NULL,
                label = NULL, labelOptions = NULL, options = pathOptions(),
                highlightOptions = NULL, data = getMapData(m))
m
```
